### ISSUE TITLE
ValueError: imTED: checkpoint path pre/Weights/ is invalid

### ISSUE THREAD

**Issue by luoyq6** [LiewFeng/imTED#2]
Hello, I would like to consult. I put MAE pre-training weights, but it still gives an error. Could you help me explain it

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/dfs/data/imTED/mmdet/models/detectors/imted.py", line 20, in __init__
    super(imTED, self).__init__(
  File "/dfs/data/imTED/mmdet/models/detectors/two_stage.py", line 48, in __init__
    self.init_weights(pretrained=pretrained)
  File "/dfs/data/imTED/mmdet/models/detectors/two_stage.py", line 68, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/dfs/data/imTED/mmdet/models/backbones/vision_transformer.py", line 132, in init_weights
    raise ValueError(f"checkpoint path {pretrained} is invalid")
ValueError: checkpoint path pre/Weights/ is invalid

**Comment by LiewFeng** [comment]
You need to modify the path of pre-trained weight in the config file, for example, [here](https://github.com/LiewFeng/imTED/blob/02d102ee435cbf66a135304745065b20b8ddec0e/configs/imted/imted_faster_rcnn_vit_base_3x_coco.py#L6).

**Comment by luoyq6** [comment]
> 您需要修改配置文件中预训练权重的路径，例如[，此处](https://github.com/LiewFeng/imTED/blob/02d102ee435cbf66a135304745065b20b8ddec0e/configs/imted/imted_faster_rcnn_vit_base_3x_coco.py#L6)。

It's been fixed, but it's still wrong
![1670920383907](https://user-images.githubusercontent.com/110521846/207265729-cfb5aac5-6290-4f7a-8217-312a085f4b22.png)

**Comment by LiewFeng** [comment]
It should be 'pre/Weights/mae...pth'.

**Comment by luoyq6** [comment]
> It should be 'pre/Weights/mae...pth'.

OK，Thanks. I'll try
