### ISSUE TITLE
项目中的库以及它们的版本号请求

### ISSUE THREAD

**Issue by HappyGoLucky6666** [LiewFeng/imTED#24]
非常感谢你们团队为目标检测领域所做的贡献。
现在我很想在我的本地端口复现出来你们的工作，但在刚开始的环境配置过程中就遇到了很多问题，有些甚至难以解决。因此，我请求你能不能给我提供一下运行们你们的模型所需要安装的库和包，以及它们的版本号，这对我非常重要。请将模型运行所需要的库和它们的版本一并向我展示，我现在在环境配制过程中被不同库的版本搞得很头疼，因为现在的很多东西都有所升级了。提前给你们说一声谢谢！

**Comment by HappyGoLucky6666** [comment]
请问能抽空回复一下我的这一请求吗@LiewFeng

**Comment by LiewFeng** [comment]
Hi, @HappyGoLucky6666 . Thank you for your interest in our work. Sorry for the late reply. You cab try with the following version and CUDA 11.1.
```
addict==2.4.0
apex
certifi==2025.1.31
charset-normalizer==3.4.1
contourpy==1.1.1
cycler==0.12.1
Cython==0.29.33
filelock==3.16.1
fonttools==4.56.0
fsspec==2025.2.0
huggingface-hub==0.29.1
idna==3.10
importlib_metadata==8.5.0
importlib_resources==6.4.5
kiwisolver==1.4.7
matplotlib==3.7.5
mmcv-full==1.3.9
mmpycocotools==12.0.3
numpy==1.24.4
opencv-python==4.11.0.86
packaging==24.2
pillow==10.4.0
platformdirs==4.3.6
pyparsing==3.1.4
python-dateutil==2.9.0.post0
PyYAML==6.0.2
requests==2.32.3
safetensors==0.5.3
six==1.17.0
terminaltables==3.1.10
timm==1.0.15
tomli==2.2.1
torch==1.10.1+cu111
torchaudio==0.10.1+cu111
torchvision==0.11.2+cu111
tqdm==4.67.1
typing_extensions==4.12.2
urllib3==2.2.3
yapf==0.40.1
zipp==3.20.2
```

**Comment by HappyGoLucky6666** [comment]
非常感谢你的回复，收到你的回答我很高兴，这对我有很大的帮助，但是我在本地配置环境的时候主要问题还是其中的apex库的兼容性问题，但是在你的回复中唯独apex库没有具体的版本，这是为什么，还是我下载任何版本都可以，这一直困惑着我，还请再给我提供帮助，谢谢！@LiewFeng

**Comment by LiewFeng** [comment]
Try with the following command.

```
git clone https://github.com/NVIDIA/apex.git
cd apex
git checkout origin/22.02-parallel-state # or another vesion
python setup.py install --cuda_ext --cpp_ext
pip3 install -v --no-cache-dir ./
```

**Comment by HappyGoLucky6666** [comment]
谢谢你的帮助，你现在就立马去试着配置一下环境。因为这个项目我是年前那时候关注的，中间做了其他一些工作，可能需要一点时间，在此期间希望我们能保持联系。

**Comment by HappyGoLucky6666** [comment]
Traceback (most recent call last):
  File "D:\imTED-main\tools\train.py", line 15, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "D:\imTED-main\mmdet\apis\__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "D:\imTED-main\mmdet\apis\inference.py", line 6, in <module>
    from mmcv.ops import RoIPool
  File "D:\Anaconda3\envs\vitdet\lib\site-packages\mmcv\ops\__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "D:\Anaconda3\envs\vitdet\lib\site-packages\mmcv\ops\bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "D:\Anaconda3\envs\vitdet\lib\site-packages\mmcv\utils\ext_loader.py", line 12, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "D:\Anaconda3\envs\vitdet\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: 找不到指定的模块。
你好，我再根据你给的一系列包和库的具体版本号后又重新配置了虚拟环境，但是在我又一次试运行train.py脚本文件后，给我报了以上错误。通过搜索我得知可能的原因是mmcv，torch，python的版本冲突问题，我只好重新在确认一遍环境中各种库的版本号对应情况，在再一次检查无误后又进行了尝试，依旧报如此错误。因此，我决定再次提出问题，这到底是怎么一回事才导致了这个错误，又该如何解决？@LiewFeng

**Comment by HappyGoLucky6666** [comment]
@LiewFeng ，你好，很抱歉再一次打扰你。我已经成功配置好了该项目的环境，不过这次我使用的是Linux系统进行的实践，之前在Windows系统上死活是配置不成功，我猜想可能是mmcv库中的ops组件出现了错误，它无法正确的进行C++等类似的编译，始终无法成功导入里面的文件，实验再三的我决定放弃，不得已转战Linux系统实践。当然，在Linux系统的环境配置依然充满了挑战性，我也是耗费了大量的时间和精力去努力实现这个项目。终于，在经历过重重困难后，今天晚上成功运行出来了这个项目的训练文件，不过运行的过程又是我的内心遭受到了沉重的打击，这个项目的训练为何需要如此多的时间。我电脑的配置是一台小小的4060ti，运行的文件是imted_faster_rcnn_vit_base_3x_coco.py，使用的数据是全部的coco数据集，结果训练的时候终端打印出来的运行日志彻底让我崩溃，下面的图片是日志的部分截图，这个结果实在是太离谱了，我真的很无助。请问这是什么原因呢？这是说我的条件压根就不允许我跑如此大的项目，还请给我解答迷津，谢谢！！！

![Image](https://github.com/user-attachments/assets/9a913f3b-0c9e-4060-81cd-dca0e9e43f4d)

**Comment by LiewFeng** [comment]
We conduct experiments on 8 * A100. You can try with 'imted_faster_rcnn_vit_small_3x_coco.py', which takes less time. Further, you can try with 1x schedule.
